# Generated by Django 4.1.5 on 2023-01-31 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="prince",
            new_name="price",
        ),
    ]
